version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify your Node.js version
    commands:
      - echo Installing NPM dependencies...
      - npm install  # Use this if you have dependencies, otherwise skip
  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...
      - mkdir -p output  # Create the output directory if it doesn't exist
      - cp -R index.html output/  # Copy index.html specifically to output
      # Add more specific copy commands if you have additional files
      # - cp -R other-file output/  # Example for other files

artifacts:
  files:
    - 'output/**/*'  # Include all files from the output directory
  base-directory: output  # Use the output directory for artifacts
