version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify your Node.js version
    commands:
      - echo Installing NPM dependencies...
      - npm install  # Use this if you have dependencies, otherwise skip
  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...
      - mkdir output  # Create a directory for final output
      - cp -R * output/  # Copy all files to the output directory

artifacts:
  files:
    - 'output/**/*'  # Include all files from the output directory
  base-directory: output  # Use the output directory for artifacts
