version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify your Node.js version
    commands:
      - echo Installing NPM dependencies...
      - npm install  # Use this if you have dependencies; skip if not needed
  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...
      - mkdir -p output  # Create the output directory
      - cp -R index.html output/  # Copy index.html to output
      - ls output/  # List files in the output directory to verify

artifacts:
  files:
    - 'output/**/*'  # Include all files from the output directory
  base-directory: output  # Specify the output directory for artifacts
